/**
 * LGTM API specification
 * The REST API for LGTM provides data so that you can customize how you integrate LGTM analysis into your workflow. It includes the following resources:   * `/` ([API root](https://lgtm.com/help/lgtm/api/api-v1#LGTM-API-specification-API-root))&mdash;get version information or download the specification in OpenAPI format.   * `/projects` ([Projects](https://lgtm.com/help/lgtm/api/api-v1#LGTM-API-specification-Projects))&mdash;list projects, get a summary of the current status for a project, or add new projects.   * `/analyses` ([Analyses](https://lgtm.com/help/lgtm/api/api-v1#LGTM-API-specification-Analyses))&mdash;get a summary of results, download all the alerts, or trigger analysis for a specific commit.   * `/codereviews` ([Code reviews](https://lgtm.com/help/lgtm/api/api-v1#LGTM-API-specification-Code-reviews))&mdash;trigger code review for a patch, and view the results.   * `/operations` ([Operations](https://lgtm.com/help/lgtm/api/api-v1#LGTM-API-specification-Operations))&mdash;get information about long-running tasks, for example, analyses or code reviews that you\'ve requested.   * `/snapshots` ([Snapshots](https://lgtm.com/help/lgtm/api/api-v1#LGTM-API-specification-Snapshots))&mdash;download and upload databases representing a snapshot of a codebase.   * `/queryjobs` ([Query jobs](https://lgtm.com/help/lgtm/api/api-v1#LGTM-API-specification-Query-jobs))&mdash;submit queries to evaluate against existing projects, and download their results.   * `/system` ([System](https://lgtm.com/help/lgtm/api/api-v1#LGTM-API-specification-System))&mdash;get information on the health or usage of the system.  For an overview and getting started topics, see [API for LGTM](https://lgtm.com/help/lgtm/api/api-for-lgtm). 
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CodereviewAlerts } from './codereviewAlerts';

export class CodereviewLanguages {
    /**
    * The language analyzed.
    */
    'language'?: string;
    /**
    * The status for analysis of this language.
    */
    'status'?: CodereviewLanguages.StatusEnum;
    /**
    * The current state of analysis of this langauge. When available, a summary of analysis results.
    */
    'statusMessage'?: string;
    /**
    * The total number of alerts introduced by the patch for this language.
    */
    '_new'?: number;
    /**
    * The total number of alerts fixed by the patch for this language.
    */
    'fixed'?: number;
    /**
    * The list of added and fixed alerts per query for this language.
    */
    'alerts'?: Array<CodereviewAlerts>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "language",
            "baseName": "language",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "CodereviewLanguages.StatusEnum"
        },
        {
            "name": "statusMessage",
            "baseName": "status-message",
            "type": "string"
        },
        {
            "name": "_new",
            "baseName": "new",
            "type": "number"
        },
        {
            "name": "fixed",
            "baseName": "fixed",
            "type": "number"
        },
        {
            "name": "alerts",
            "baseName": "alerts",
            "type": "Array<CodereviewAlerts>"
        }    ];

    static getAttributeTypeMap() {
        return CodereviewLanguages.attributeTypeMap;
    }
}

export namespace CodereviewLanguages {
    export enum StatusEnum {
        Pending = <any> 'pending',
        Failure = <any> 'failure',
        Success = <any> 'success'
    }
}
